package view;


import controller.Client;

import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Admin
 */
public class HomePageForm extends javax.swing.JFrame {
    /**
     * Creates new form GiaoDienChinhFrm
     */
    public HomePageForm() {
        initComponents();
        this.setTitle("Caro Game Nhóm 5");
        this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        jLabel_NickNameValue.setText(Client.user.getNickname());
        jLabel_NumberOfWinValue.setText(Integer.toString(Client.user.getNumberOfWin()));
        jlabel_NumberOfGameValue.setText(Integer.toString(Client.user.getNumberOfGame()));
        jLabel_Image.setIcon(new ImageIcon("assets/avatar/" + Client.user.getAvatar() + ".jpg"));
//        sendMessageButton.setIcon(new ImageIcon("assets/image/send2.png"));
        jTextArea_MessageTextArea.setEditable(false);
        if (Client.user.getNumberOfGame() == 0) {
            jLabel_WinRatioValue.setText("-");
        } else {
            jLabel_WinRatioValue.setText(String.format("%.2f", (float) Client.user.getNumberOfWin() / Client.user.getNumberOfGame() * 100) + "%");
        }
        jLabel_DrawValue.setText("" + Client.user.getNumberOfDraw());
        jLabel_MarkValue.setText("" + (Client.user.getNumberOfGame() + Client.user.getNumberOfWin() * 10));
        jLabel_RankValue.setText("" + Client.user.getRank());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jButton_QuickGame = new javax.swing.JButton();
        jButton_GoRoom = new javax.swing.JButton();
        jButton_CreateRoom = new javax.swing.JButton();
        jButton_FindRoom = new javax.swing.JButton();
        jButton_PlayWithBot = new javax.swing.JButton();
        jButton_FriendList = new javax.swing.JButton();
        jButton_ScoreBoard = new javax.swing.JButton();
        jButton_ScoreBot = new javax.swing.JButton();
        jButton_ExitGame = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_NickName = new javax.swing.JLabel();
        jLabel_NumberOfWin = new javax.swing.JLabel();
        jLabel_NickNameValue = new javax.swing.JLabel();
        jLabel_NumberOfWinValue = new javax.swing.JLabel();
        jLabel_Image = new javax.swing.JLabel();
        jlabel_NumberOfGameValue = new javax.swing.JLabel();
        jLabel_NumberOfGame = new javax.swing.JLabel();
        jLabel_Mark = new javax.swing.JLabel();
        jLabel_MarkValue = new javax.swing.JLabel();
        jLabel_Rank = new javax.swing.JLabel();
        jLabel_RankValue = new javax.swing.JLabel();
        jLabel_WinRatio = new javax.swing.JLabel();
        jLabel_WinRatioValue = new javax.swing.JLabel();
        jLabel_Draw = new javax.swing.JLabel();
        jLabel_DrawValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_MessageTextArea = new javax.swing.JTextArea();
        jTextField_MessageInput = new javax.swing.JTextField();
        jButton_SendMessage = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Tittle = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jButton_QuickGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_QuickGame.setForeground(new java.awt.Color(255, 51, 51));
        jButton_QuickGame.setText("Chơi nhanh");
        jButton_QuickGame.setContentAreaFilled(false);
        jButton_QuickGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_QuickGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuickGameActionPerformed(evt);
            }
        });

        jButton_GoRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_GoRoom.setForeground(new java.awt.Color(255, 51, 51));
        jButton_GoRoom.setText("Vào phòng");
        jButton_GoRoom.setContentAreaFilled(false);
        jButton_GoRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_GoRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GoRoomActionPerformed(evt);
            }
        });

        jButton_CreateRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_CreateRoom.setForeground(new java.awt.Color(255, 51, 51));
        jButton_CreateRoom.setText("Tạo Phòng");
        jButton_CreateRoom.setContentAreaFilled(false);
        jButton_CreateRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_CreateRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CreateRoomActionPerformed(evt);
            }
        });

        jButton_FindRoom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_FindRoom.setForeground(new java.awt.Color(255, 51, 51));
        jButton_FindRoom.setText("Tìm phòng");
        jButton_FindRoom.setContentAreaFilled(false);
        jButton_FindRoom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_FindRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FindRoomActionPerformed(evt);
            }
        });

        jButton_PlayWithBot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_PlayWithBot.setForeground(new java.awt.Color(255, 51, 51));
        jButton_PlayWithBot.setText("Chơi với máy");
        jButton_PlayWithBot.setContentAreaFilled(false);
        jButton_PlayWithBot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_PlayWithBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PlayWithBotActionPerformed(evt);
            }
        });

        jButton_FriendList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_FriendList.setForeground(new java.awt.Color(255, 51, 51));
        jButton_FriendList.setText("Danh sách bạn bè");
        jButton_FriendList.setContentAreaFilled(false);
        jButton_FriendList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_FriendList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FriendListActionPerformed(evt);
            }
        });

        jButton_ScoreBoard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_ScoreBoard.setForeground(new java.awt.Color(255, 51, 51));
        jButton_ScoreBoard.setText("Bảng xếp hạng");
        jButton_ScoreBoard.setContentAreaFilled(false);
        jButton_ScoreBoard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ScoreBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ScoreBoardActionPerformed(evt);
            }
        });

        jButton_ScoreBot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_ScoreBot.setForeground(new java.awt.Color(255, 51, 51));
        jButton_ScoreBot.setText("Đăng xuất");
        jButton_ScoreBot.setContentAreaFilled(false);
        jButton_ScoreBot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ScoreBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ScoreBotActionPerformed(evt);
            }
        });

        jButton_ExitGame.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton_ExitGame.setForeground(new java.awt.Color(255, 51, 51));
        jButton_ExitGame.setText("Thoát Game");
        jButton_ExitGame.setContentAreaFilled(false);
        jButton_ExitGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_ExitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitGameActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 5));

        jLabel_NickName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NickName.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NickName.setText("NickName");
        jLabel_NickName.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jLabel_NickNameAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel_NumberOfWin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NumberOfWin.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NumberOfWin.setText("Số ván thắng");

        jLabel_NickNameValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NickNameValue.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NickNameValue.setText("{day la Nick name}");

        jLabel_NumberOfWinValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NumberOfWinValue.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NumberOfWinValue.setText("{day la so van thang}");

        jLabel_Image.setBackground(new java.awt.Color(204, 204, 204));

        jlabel_NumberOfGameValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlabel_NumberOfGameValue.setForeground(new java.awt.Color(0, 0, 0));
        jlabel_NumberOfGameValue.setText("{day la so van da choi}");

        jLabel_NumberOfGame.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_NumberOfGame.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NumberOfGame.setText("Số ván đã chơi");

        jLabel_Mark.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Mark.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Mark.setText("Điểm");

        jLabel_MarkValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_MarkValue.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_MarkValue.setText("{day la diem}");

        jLabel_Rank.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Rank.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Rank.setText("Thứ hạng");

        jLabel_RankValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_RankValue.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_RankValue.setText("{day la thu hang}");

        jLabel_WinRatio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_WinRatio.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_WinRatio.setText("Tỉ lệ thắng");

        jLabel_WinRatioValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_WinRatioValue.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_WinRatioValue.setText("{day la ti le thang}");

        jLabel_Draw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_Draw.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Draw.setText("Số ván hòa");

        jLabel_DrawValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_DrawValue.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_DrawValue.setText("{day la so van hoa}");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NumberOfWin)
                            .addComponent(jLabel_NickName)
                            .addComponent(jLabel_NumberOfGame, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_NickNameValue)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlabel_NumberOfGameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel_NumberOfWinValue)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Mark, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Rank)
                            .addComponent(jLabel_WinRatio)
                            .addComponent(jLabel_Draw))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_DrawValue)
                            .addComponent(jLabel_WinRatioValue)
                            .addComponent(jLabel_MarkValue)
                            .addComponent(jLabel_RankValue))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_NickNameValue)
                            .addComponent(jLabel_NickName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jlabel_NumberOfGameValue))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_NumberOfGame)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NumberOfWinValue)
                            .addComponent(jLabel_NumberOfWin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Draw)
                            .addComponent(jLabel_DrawValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_WinRatio)
                            .addComponent(jLabel_WinRatioValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_MarkValue)
                            .addComponent(jLabel_Mark))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_Rank)
                            .addComponent(jLabel_RankValue))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea_MessageTextArea.setColumns(20);
        jTextArea_MessageTextArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextArea_MessageTextArea.setRows(5);
        jTextArea_MessageTextArea.setText("<<Tin nhắn và tin tức>>\n");
        jScrollPane1.setViewportView(jTextArea_MessageTextArea);

        jTextField_MessageInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_MessageInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_MessageInputKeyPressed(evt);
            }
        });

        jButton_SendMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_SendMessage.setText("Gửi");
        jButton_SendMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_SendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SendMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_MessageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_SendMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_QuickGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_GoRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_CreateRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_FindRoom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ScoreBoard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ScoreBot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_ExitGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_PlayWithBot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_FriendList, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_MessageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_SendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_QuickGame)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_GoRoom)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_CreateRoom)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_FindRoom)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_PlayWithBot)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_FriendList)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ScoreBoard)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ScoreBot)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ExitGame)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel_Tittle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel_Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Tittle.setText("GAME CARO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Tittle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Tittle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_NickNameAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel_NickNameAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_NickNameAncestorMoved

    private void jButton_CreateRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CreateRoomActionPerformed
        int res = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đặt mật khẩu cho phòng không?", "Tạo phòng", JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            Client.closeView(Client.View.HOMEPAGE);
            Client.openView(Client.View.CREATE_ROOM_PASSWORD);
        } else if (res == JOptionPane.NO_OPTION) {
            try {
                Client.socketHandle.write("create-room,");
                Client.closeView(Client.View.HOMEPAGE);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton_CreateRoomActionPerformed

    private void jButton_FindRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FindRoomActionPerformed
        try {
            Client.closeView(Client.View.HOMEPAGE);
            Client.openView(Client.View.ROOM_LIST);
            Client.socketHandle.write("view-room-list,");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton_FindRoomActionPerformed

    private void jButton_ScoreBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ScoreBoardActionPerformed
        Client.openView(Client.View.RANK);
    }//GEN-LAST:event_jButton_ScoreBoardActionPerformed

    private void jButton_ScoreBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ScoreBotActionPerformed
        try {
            Client.socketHandle.write("offline," + Client.user.getID());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
        Client.closeView(Client.View.HOMEPAGE);
        Client.openView(Client.View.LOGIN);
    }//GEN-LAST:event_jButton_ScoreBotActionPerformed

    private void jButton_ExitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitGameActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton_ExitGameActionPerformed

    private void jButton_FriendListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FriendListActionPerformed
        Client.closeView(Client.View.HOMEPAGE);
        Client.openView(Client.View.FRIEND_LIST);
    }//GEN-LAST:event_jButton_FriendListActionPerformed

    private void jButton_QuickGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuickGameActionPerformed
        Client.closeView(Client.View.HOMEPAGE);
        Client.openView(Client.View.FIND_ROOM);
    }//GEN-LAST:event_jButton_QuickGameActionPerformed

    private void jButton_PlayWithBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PlayWithBotActionPerformed
        // TODO add your handling code here:
        Client.openView(Client.View.GAME_AI);
    }//GEN-LAST:event_jButton_PlayWithBotActionPerformed

    private void jButton_GoRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GoRoomActionPerformed
        Client.openView(Client.View.ROOM_NAME_FRM);
    }//GEN-LAST:event_jButton_GoRoomActionPerformed

    private void jButton_SendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SendMessageActionPerformed
        sendMessage();
    }//GEN-LAST:event_jButton_SendMessageActionPerformed

    private void jTextField_MessageInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MessageInputKeyPressed
        if (evt.getKeyCode() == 10) {
            sendMessage();
        }
    }//GEN-LAST:event_jTextField_MessageInputKeyPressed

    private void sendMessage() {
        try {
            if (jTextField_MessageInput.getText().isEmpty()) {
                throw new Exception("Vui lòng nhập nội dung tin nhắn");
            }
            String temp = jTextArea_MessageTextArea.getText();
            temp += "Tôi: " + jTextField_MessageInput.getText() + "\n";
            jTextArea_MessageTextArea.setText(temp);
            Client.socketHandle.write("chat-server," + jTextField_MessageInput.getText());
            jTextField_MessageInput.setText("");
            jTextArea_MessageTextArea.setCaretPosition(jTextArea_MessageTextArea.getDocument().getLength());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }

    public void addMessage(String message) {
        String temp = jTextArea_MessageTextArea.getText();
        temp += message + "\n";
        jTextArea_MessageTextArea.setText(temp);
        jTextArea_MessageTextArea.setCaretPosition(jTextArea_MessageTextArea.getDocument().getLength());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_CreateRoom;
    private javax.swing.JButton jButton_ExitGame;
    private javax.swing.JButton jButton_FindRoom;
    private javax.swing.JButton jButton_FriendList;
    private javax.swing.JButton jButton_GoRoom;
    private javax.swing.JButton jButton_PlayWithBot;
    private javax.swing.JButton jButton_QuickGame;
    private javax.swing.JButton jButton_ScoreBoard;
    private javax.swing.JButton jButton_ScoreBot;
    private javax.swing.JButton jButton_SendMessage;
    private javax.swing.JLabel jLabel_Draw;
    private javax.swing.JLabel jLabel_DrawValue;
    private javax.swing.JLabel jLabel_Image;
    private javax.swing.JLabel jLabel_Mark;
    private javax.swing.JLabel jLabel_MarkValue;
    private javax.swing.JLabel jLabel_NickName;
    private javax.swing.JLabel jLabel_NickNameValue;
    private javax.swing.JLabel jLabel_NumberOfGame;
    private javax.swing.JLabel jLabel_NumberOfWin;
    private javax.swing.JLabel jLabel_NumberOfWinValue;
    private javax.swing.JLabel jLabel_Rank;
    private javax.swing.JLabel jLabel_RankValue;
    private javax.swing.JLabel jLabel_Tittle;
    private javax.swing.JLabel jLabel_WinRatio;
    private javax.swing.JLabel jLabel_WinRatioValue;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_MessageTextArea;
    private javax.swing.JTextField jTextField_MessageInput;
    private javax.swing.JLabel jlabel_NumberOfGameValue;
    // End of variables declaration//GEN-END:variables
}
